# Generated by Django 5.2.5 on 2025-09-02 18:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_processstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutsection",
            name="main_content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Main Content"),
        ),
    ]
